# Generated by Django 3.1.3 on 2020-11-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pics',
            name='images',
        ),
        migrations.AddField(
            model_name='pics',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
