# Generated by Django 3.1.3 on 2020-11-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pics',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='pics',
            name='location',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
