# Generated by Django 3.1.3 on 2020-11-15 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20201115_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pics',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pics.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pics',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pics.categories'),
            preserve_default=False,
        ),
    ]
