# Generated by Django 3.1.3 on 2020-11-17 09:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20201117_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='images',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255),
        ),
    ]
